version: '3'

services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres@database/postgres
    links:
      - database

  database:
    image: postgres:10-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

volumes:
  pgdata:
    driver: local

